[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "711b06a2225f847cfff996a9359fa90fc51bb385"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "d4188fd1301741b7a945ab86e98da5126d3d69f5b1b75e46d3036cc30609eb57"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df9b2e6247ed49ef7736f69b00fc0031dc41d95d"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "fecd56180d1185f8aa067a2afa53ada46ced66e932adc2867ed4ddfe7ea984b8"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80c183a4e29f71080e90bc9acb4436a55fb6e9a7"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "f986aaefdb05db2608bfcf137aa0d3427d4a7f0144441cef4bc4d46aead60b3c"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.aarch64-linux-musl-cxx03.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "341b5d78e6eb18350182cd3a12a285915530cf17"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "62d86c89e20c4f3ffd1ad484995a57c0714f2c40931004912414ad26da15ef1d"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.aarch64-linux-musl-cxx11.tar.gz"
[[libnode]]
arch = "x86_64"
git-tree-sha1 = "b0f7d423c4ada5aeac1df4b5767b5208d4537d47"
os = "macos"

    [[libnode.download]]
    sha256 = "e9c5bb9512f0c5ad2aef6043c9b24683cd9d6ac937a5467908d7a9d37821ac68"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.x86_64-apple-darwin.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90476e0878570122d5ceb7c6cdd98ed9affca6bc"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "8662969fa39281e6623e6dd09f71a7180487002569dbbf11cf65da1a692da4f2"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33ee35b0ee706cd9df6f614938757884105636bb"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "0afd55533d138846bc19e7fd8c5b3acc5670bf4f8c3718e4503008f0df3471c8"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26c20195d8c75cdf4d9271559f68fa5042107c05"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "a3492f45918faa5bcd89d23dc51c94c566b8fd4398b85309da80a4a46f33060a"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.x86_64-linux-musl-cxx03.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc40c5073357058e499034e1b5de915e40dce91b"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "4e02a05e51639410047c7c8b25023d2a9dfba05aae31391a15eaa0ec68c0c85a"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.x86_64-linux-musl-cxx11.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abe782cf998038ea962b735d3dc4823f277f38e6"
os = "windows"

    [[libnode.download]]
    sha256 = "b740693d6964b9e5d13cf1178e07608c026fef137597263836fa1fbf51ac32e0"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abe782cf998038ea962b735d3dc4823f277f38e6"
os = "windows"

    [[libnode.download]]
    sha256 = "b740693d6964b9e5d13cf1178e07608c026fef137597263836fa1fbf51ac32e0"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v18.12.1+0/libnode.v18.12.1.x86_64-w64-mingw32-cxx11.tar.gz"
