[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a23bef91d3813ec2201ac5b7d0be79a419b11b91"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "42d56e26877067ea6e0a151c7439cce99a39b22c86e8e905227eb03497af6362"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47999794ed83363d38ba045802c4bf7597bf7ad3"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "14ef90c4b53189d85d9f15deaa495ce6212fe500c65b41a6bfcb04541d18c02b"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21bb9d5657cee22fd2781fd4612aed05e0edc650"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "8ae6e28ef9617c50482c349b6d5d2052bbc74c3a49326c0ecb84d254db402440"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.aarch64-linux-musl-cxx03.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ecfefad988fccb2782dc1ce1b5fa272c6184169d"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "86a4967dd8aedb24986465d8a07b8600419acbc5b6a17ff2743436eb7b48efe9"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.aarch64-linux-musl-cxx11.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "538b18a6f0a2ac90fb115ff76b7725813f0671ed"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "d821ef0ed4f12af7f6bc0649bbae3626728a8e3fbcead18f07790d2a025f2d21"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba0554f5887825d9f289fe7d9213a1e0d21f7292"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "4a51eb738a9ada71796378746a97d8ef5fbcfc2ebd056ea88b236e9cc2b0da52"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2d65483e798566d55b1c007f020a9f491dc90c4"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "35b76bd74deec5bef886e98bc11148c2db4eed22a36a1dca87a4a983471fd62d"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.x86_64-linux-musl-cxx03.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21613af21615e72c51e5e06466592e448cf5fe89"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "c2a4b725789936e829e5d01da13699c1dd60d1ef43d17917cc65ec11ea3795a1"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.14.0+0/libnode.v16.14.0.x86_64-linux-musl-cxx11.tar.gz"
