[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bace1035577ef9e0eeebe16875e87904f96d0a0b"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "872aa70b406b9d77c8e1de284b2aa7c3acb6cbf65a3925aeeebb7cab2d63bf85"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d7d924c3a087949f8e32a2400447017bbecac57"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "7cd5fc4c9a0cb1ab0f10668b7c1320257e4b2a3142acaea07083681ca68d88ad"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40f9898859150294ebfe626b39075fe5b7f56b56"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "a46ff6ab5cf56170bff127a5c31c41a8d4d5a45c10398a1f241513e7670bcf93"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.aarch64-linux-musl-cxx03.tar.gz"
[[libnode]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe151095d0527614ddcbf522684edc3b612fee68"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "ab7d0fce3fb837902be53e9cea859da3b04ba3a62f2368e8597d9476bd3bc3a1"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.aarch64-linux-musl-cxx11.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "812af797612e99e70110602bde10d2b40d232f90"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "add81e3af3cf64a0db07b30d01c52231f024801d1b661422f368baaf8d92deb5"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97aeaf23cf410621b0e1efe59c50cf366b133e39"
libc = "glibc"
os = "linux"

    [[libnode.download]]
    sha256 = "fb1c1d4d6f95ca6bd620cd154bfd27971f7e89549ee352590a0dec01e36515b3"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d66a322eb4581c358f95e40f64cdd7d044b0bcbc"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "a4025388e7df1f59b24fc8fa7cab071bc30fc71b86ebfffd15d77a1afcac6f02"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.x86_64-linux-musl-cxx03.tar.gz"
[[libnode]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77bd36d92fcb930eca029e29b804b62b90ab2bb7"
libc = "musl"
os = "linux"

    [[libnode.download]]
    sha256 = "98194e1e4edef34ae871b73349285c40b6fe324816b1f297f52c39328e3889a0"
    url = "https://github.com/JuliaBinaryWrappers/libnode_jll.jl/releases/download/libnode-v16.17.0+0/libnode.v16.17.0.x86_64-linux-musl-cxx11.tar.gz"
